<?php 
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://crazy-21winter019--acvpartial.sandbox.my.salesforce.com/services/data/v57.0/query/?q=SELECT+FirstName+from+Contact');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Authorization: Bearer 00D8C0000008hmg!AR4AQDl3o58TBrBGZ8mEnvte5Cp9FMXCOkfIlO.FzWK_R8DRY8onT1JgilwhE5n3tz.eqfm8QjoViHK8W5sn851iI67PnEA.';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

echo "----------<pre>";
print_r($result);
echo "</pre>------------";

if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

?>